/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectPathRouteImport } from './routes/projects.$projectPath'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs.$jobId.index'
import { Route as JobsJobIdSessionsSessionIdRouteImport } from './routes/jobs.$jobId.sessions.$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectPathRoute = ProjectsProjectPathRouteImport.update({
  id: '/projects/$projectPath',
  path: '/projects/$projectPath',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdSessionsSessionIdRoute =
  JobsJobIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => JobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/projects/$projectPath': typeof ProjectsProjectPathRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/jobs/$jobId/sessions/$sessionId': typeof JobsJobIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/projects/$projectPath': typeof ProjectsProjectPathRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
  '/jobs/$jobId/sessions/$sessionId': typeof JobsJobIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/projects/$projectPath': typeof ProjectsProjectPathRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
  '/jobs/$jobId/sessions/$sessionId': typeof JobsJobIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/jobs/$jobId'
    | '/projects/$projectPath'
    | '/jobs/$jobId/'
    | '/jobs/$jobId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/projects/$projectPath'
    | '/jobs/$jobId'
    | '/jobs/$jobId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/jobs/$jobId'
    | '/projects/$projectPath'
    | '/jobs/$jobId/'
    | '/jobs/$jobId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  ProjectsProjectPathRoute: typeof ProjectsProjectPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectPath': {
      id: '/projects/$projectPath'
      path: '/projects/$projectPath'
      fullPath: '/projects/$projectPath'
      preLoaderRoute: typeof ProjectsProjectPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/sessions/$sessionId': {
      id: '/jobs/$jobId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/jobs/$jobId/sessions/$sessionId'
      preLoaderRoute: typeof JobsJobIdSessionsSessionIdRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
  JobsJobIdSessionsSessionIdRoute: typeof JobsJobIdSessionsSessionIdRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
  JobsJobIdSessionsSessionIdRoute: JobsJobIdSessionsSessionIdRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  ProjectsProjectPathRoute: ProjectsProjectPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
